- LICENSE
- README.md
> add LICENSE and fix typo in README

- .gitignore
- README.md
CHANGELOG_BEGIN
CHANGELOG_END
Added a section on how to make changes to the docs & changed the repo address in the instructions on how to clone.
> Added a section on how to make changes to the docs

- docs/build.sh
- docs/setup-sphinx-source-tree.sh
As requested by Craig on Slack.
> change PDF file name

- docs/index/create-daml-apps/developer-tools/index.rst
- docs/index/index.rst
It is being retained as part of Developer Tools
> Relocate the Deploy to a Generic Daml Ledger page

- .circleci/config.yml
We can't build new docs until some version of https://github.com/DACH-NY/canton/pull/10571 gets merged.
cc @daravep
> ignore current snapshot

- docs/index/deploy-daml/download/index.rst
- docs/index/deploy-daml/install-ledger/index.rst
- docs/index/index.rst
- docs/index/operate-a-daml-ledger/administration-introduction/index.rst
- docs/index/operate-a-daml-ledger/advanced-operations/index.rst
- docs/index/operate-a-daml-ledger/canton-administration-quickstart/index.rst
- docs/index/operate-a-daml-ledger/common-tasks/index.rst
Finding homes for all pages not previously represented; removing links formatted as outside links where this causes a problem.
> Sorting the 'To Sort' pages

- docs/index/deploy-daml/intro/index.rst
> Typo fixes in TOC

- LATEST
- docs/index/index.rst
Removes the pages being removed as part of https://github.com/digital-asset/daml/pull/15337
changelog_begin
changelog_end
> Remove outdated content

- .circleci/config.yml
- LATEST
- docs/build.sh
- docs/download.sh
- docs/index/daml-finance/intro.rst
- docs/index/index.rst
- docs/setup-sphinx-source-tree.sh
Link to daml finance's github-pages instead.
> Remove daml-finance from the docs build

- LATEST
- docs/setup-sphinx-source-tree.sh
This reverts commit 4cbe6eed795c6b43b1862aa26a8306de6ba89c96.
> back to 2.5.0

- .circleci/config.yml
This will get rid of stale files.
> remove folder before pushing it

- README.md
Full instructions on how to deal with situations in which you need to make a change to an earlier version.
> adding backport instructions

- LATEST
- docs/index/_toc.yml
Updates to the explicit `toc` unfortunately have to be done manually at the moment 😢
> Bump daml finance to 1.0.3

- LATEST
Includes https://github.com/digital-asset/daml/pull/15873.
> 2.5.0 final version (maybe)

- LATEST
Specifically https://github.com/digital-asset/daml/pull/15851/files.
> 2.5.0: add one custom-views docs change

- .circleci/config.yml
No idea what's going wrong here so hopefully printing all the things will help.
> cron: add debug logs

- .circleci/config.yml
- README.md
- bin/build
- bin/download
- bin/live-preview
- bin/setup-sphinx-source-tree
Reducing duplication in preparation for future improvements.
> clean up download script

- README.md
Add a section mentioning when and how to reindex the site search, such as when a new version of the docs is released.
> add mention of search reindexing

- README.md
- versions.json
Bumping and updating the README with `bump` script info.
> Run bump and update README

- .circleci/config.yml
Hopefully this is the last issue.
> fix snapshots credentials

- docs/2.6.0/docs/app-dev/bindings-ts/index.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/disaster-recovery.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/daml-ha-overview.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/ha-in-the-cloud.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/implementing-ha.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/introduction.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/understanding-ha.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst
A review of the newly created pages for HA and Scaling and for DR.
> Tech Writing review of the HA/Scaling and DR pages

- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/disaster-recovery.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/understanding-ha.rst
- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/main-menu.rst
Please approve @garyverhaegen-da. Thank you.
> a few fixes after review

- docs/2.6.0/docs/app-dev/bindings-java/codegen.rst
- docs/2.6.0/docs/app-dev/bindings-java/index.rst
- docs/2.6.0/docs/concepts/time.rst
- docs/2.6.0/docs/daml/intro/5_Restrictions.rst
See original PRs for history:
* https://github.com/digital-asset/daml/pull/16127
* https://github.com/digital-asset/daml/pull/16146
* https://github.com/digital-asset/daml/pull/16236
cc @wallacekelly-da
> Apply Wallace's patches

- docs/2.6.0/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/intro.rst
- docs/2.7.0/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/intro.rst
Remove the disclaimer that warns about the section being out-of-date.
> remove disclaimer about being out-of-date

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-instrument-generic.rst
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-instrument-option.rst
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-lifecycle.rst
- docs/2.7.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-generic.rst
- docs/2.7.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-option.rst
- docs/2.7.0/docs/daml-finance/packages/interfaces/daml-finance-interface-lifecycle.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/equity-extension.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/option-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/660
Fixes https://github.com/digital-asset/daml-finance/issues/676
Fixes https://github.com/digital-asset/daml-finance/issues/679
Depends on https://github.com/digital-asset/daml-finance/pull/678
> Daml Finance doc update: Option package and Rights Issue / Subscription

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-instrument-option.rst
- docs/2.7.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-option.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/equity-extension.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/option-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/685
Fixes https://github.com/digital-asset/daml-finance/issues/687
> Document dividend options

- docs/2.6.0/docs/daml/intro/99_NextSteps.rst
- docs/2.7.0/docs/daml/intro/99_NextSteps.rst
> fix dead link

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-instrument-bond.rst
- docs/2.7.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-bond.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/bond-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/723
> Document Callable Bonds

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/bond-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/758
> Update callable bond tutorial

- docs/2.6.1/docs/app-dev/authorization.rst
- docs/2.7.0/docs/app-dev/authorization.rst
change "adminstrate" to "administer"
> change one word

- docs/2.7.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-equity.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/equity-extension.rst
Fixes https://github.com/digital-asset/daml-finance/issues/721
> Rename DeclareDividend (docs.daml.com)

- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-instrument-equity.rst
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-lifecycle.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/bond-extension.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/contingent-claims-instrument.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/equity-extension.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/generic-extension.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/intermediated-lifecycling.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/option-extension.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/swap-extension.rst
Fixes https://github.com/digital-asset/daml-finance/issues/722
> Replace text references to test files by clickable URLs (docs.daml.com)

- docs/2.6.1/docs/daml/reference/contract-keys.rst
- docs/2.7.0/docs/daml/reference/contract-keys.rst
make it clearer about the contract id changing
> add a phrase about the contract id

- docs/2.6.1/docs/daml/resource-management/latency-and-throughput.rst
- docs/2.6.1/docs/getting-started/installation.rst
- docs/2.7.0/docs/getting-started/installation.rst
> fix link on root

- docs/2.7.0/docs/daml-finance/concepts/lifecycling.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/bond-extension.rst
Fixes https://github.com/digital-asset/daml-finance/issues/784
> Describe lifecycling of hybrid (election&time-based) instruments

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-instrument-option.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/bond-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/790
> Describe compounded SOFR for callable bonds (docs.daml.com)

- docs/2.7.0/docs/daml-finance/tutorials/instrument-modeling/bond-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/796
> Improve Callable Bond documentation (docs.daml.com)

- docs/2.7.0/docs/daml-finance/tutorials/instrument-extension-packages/bond-extension.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/818
> Document notice days for callable bonds

- docs/2.5.5/docs/index/_toc.yml
- docs/2.6.4/_toc.yml
- docs/2.7.0/_toc.yml
The current position is not displayed as the nesting level is too deep.
> move oauth2 page up in toc

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/packages/implementations/daml-finance-claims.rst
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/822
> Add Util.Date to package level docs

- docs/2.7.0/docs/daml-finance/tutorials/advanced-topics/lifecycling/intermediated-lifecycling.rst
- docs/2.7.0/docs/daml-finance/tutorials/getting-started/settlement.rst
Fixes https://github.com/digital-asset/daml-finance/issues/733
> Describe how to cancel settlement

- docs/2.7.0/docs/daml-finance/overview/architecture.rst
Fixes https://github.com/digital-asset/daml-finance/issues/857
> Clarify upgrade process

- docs/2.7.0/docs/daml-finance/reference/patterns.rst
Fixes https://github.com/digital-asset/daml-finance/issues/850
> Describe the Factory pattern in the new Patterns section of the docs

- docs/2.6.4/_toc.yml
- docs/2.6.4/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/intro.rst
- docs/2.6.4/docs/deploy-daml/infrastructure-architecture/high-availability/main-menu.rst
- docs/2.6.4/docs/deploy-daml/infrastructure-architecture/high-availability/production.rst
- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/intro.rst
- docs/2.7.0/docs/deploy-daml/infrastructure-architecture/high-availability/main-menu.rst
- docs/2.7.0/docs/deploy-daml/infrastructure-architecture/high-availability/production.rst
Add links to submenus plus a little text to three HA pages that were previously bare and seemed blank to viewers.
> add text and links to 3 HA pages

- .circleci/config.yml
I'm not sure what the default state of the dropdown will be.
> add dev preview to dropdown

- docs/2.7.0/_toc.yml
- docs/2.7.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/878
> Bump daml finance version to pre-release assembly

- docs/2.7.0/docs/concepts/glossary.rst
Discovered while working on the internal glossary.
> Typo fixes in the Glossary

- docs/2.7.0/docs/daml-finance/tutorials/instrument-extension-packages/fixed-rate-bond.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-extension-packages/intro.rst
Relates to https://github.com/digital-asset/daml-finance/issues/892
> Update instrument tutorial

- docs/2.7.0/docs/canton/usermanual/performance.rst
Fixing a few typos and implementing Grammarly suggestions
> Typo fixes - scaling and performance

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/tutorials/instrument-extension-packages/fixed-rate-bond.rst
- docs/2.7.0/docs/daml-finance/tutorials/instrument-extension-packages/floating-rate-bond.rst
Fixes https://github.com/digital-asset/daml-finance/issues/901
> Write an e2e tutorial on Observations

- docs/2.7.0/docs/app-dev/explicit-contract-disclosure.rst
Add a few sentences to give a high-level introduction to this new feature.
> add intro for explicit contract disclosure

- docs/2.6.5/versions.json
I re-generated the code documentation we use in `2.6` for Daml Finance using the latest SDK snapshot. This brings in a bunch of improvements from @samuel-williams-da
> Update Daml Finance version for `2.6`

- docs/2.7.0/docs/daml-finance/tutorials/getting-started/holding.rst
- docs/2.7.0/docs/daml-finance/tutorials/getting-started/intro.rst
Fixes https://github.com/digital-asset/daml-finance/issues/194
> Move instructions to download getting started project

- docs/2.7.0/docs/canton/usermanual/troubleshooting_guide.rst
- 1st commit the actual changes
- 2nd commit whitespaces removal
> Changes due to tracing in lapi.

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/tutorials/settlement/intermediated.rst
- docs/2.7.0/docs/daml-finance/tutorials/settlement/intro.rst
Fixes https://github.com/digital-asset/daml-finance/issues/730
> Tutorial intermediated settlement

- docs/2.7.0/docs/canton/architecture/domains/domains.rst
- docs/2.8.0/docs/canton/architecture/domains/domains.rst
Remove the section about Performance under Non-Functional Requirements
> remove Canton TPS section

- docs/2.7.0/_toc.yml
- docs/2.7.0/docs/daml-finance/index.rst
- docs/2.7.0/docs/daml-finance/instruments/bond-extension.rst
- docs/2.7.0/docs/daml-finance/instruments/generic-instrument.rst
- docs/2.7.0/docs/daml-finance/instruments/intro.rst
- docs/2.7.0/docs/daml-finance/instruments/option-extension.rst
- docs/2.7.0/docs/daml-finance/instruments/swap-extension.rst
- docs/2.7.0/docs/daml-finance/instruments/token-instrument.rst
- docs/2.7.0/docs/daml-finance/overview/intro.rst
- docs/2.7.0/docs/daml-finance/tutorials/getting-started/intro.rst
- docs/2.7.0/docs/daml-finance/tutorials/lifecycling/intro.rst
- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/basic-builders.rst
- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/basic-combinators.rst
- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/intro.rst
- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/observations.rst
- docs/2.7.0/docs/daml-finance/tutorials/settlement/intro.rst
- docs/2.7.0/versions.json
Still pending, potentially for a subsequent PR
- fill placeholders in the `Instruments` section for `Token` and `Generic` instruments
Fixes https://github.com/digital-asset/daml-finance/issues/797, https://github.com/digital-asset/daml-finance/issues/755
Addresses most of https://github.com/digital-asset/daml-finance/issues/608
> Payoff modeling tutorials

- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/basic-builders.rst
- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/intro.rst
- docs/2.7.0/docs/daml-finance/tutorials/payoff-modeling/observations.rst
- docs/2.7.0/docs/daml-finance/tutorials/settlement/intermediated.rst
- docs/2.7.0/docs/daml-finance/tutorials/settlement/internal.rst
- docs/2.7.0/docs/daml-finance/tutorials/settlement/transfer.rst
Backport the recent tutorial updates from v2.8 to v2.7.
> Backport tutorial updates

- docs/2.8.0/docs/canton/usermanual/installation.rst
- docs/2.8.0/docs/canton/usermanual/repairing.rst
Addresses one of the problems highlighted in https://github.com/DACH-NY/canton/issues/13566
> Use indicative mode in phrasing, switch to pg instead of h2

- docs/2.7.0/docs/canton/usermanual/security.rst
- docs/2.8.0/docs/canton/usermanual/security.rst
Some small changes to the docs after another read-through and based on some external feedback.
> Small changes to KMS documentation

- docs/2.7.0/docs/query/pqs-user-guide.rst
- docs/2.8.0/docs/query/pqs-user-guide.rst
Tweaks based on Vlad's feedback
> Tweaks based on Vlads input

- docs/2.8.0/_toc.yml
- docs/2.8.0/docs/daml-finance/instruments/bond.rst
- docs/2.8.0/docs/daml-finance/instruments/equity.rst
- docs/2.8.0/docs/daml-finance/instruments/generic.rst
- docs/2.8.0/docs/daml-finance/instruments/intro.rst
- docs/2.8.0/docs/daml-finance/instruments/option.rst
- docs/2.8.0/docs/daml-finance/instruments/structured-product.rst
- docs/2.8.0/docs/daml-finance/instruments/swap.rst
- docs/2.8.0/docs/daml-finance/instruments/token.rst
- docs/2.8.0/docs/daml-finance/packages/implementations/daml-finance-instrument-option.rst
- docs/2.8.0/docs/daml-finance/packages/implementations/daml-finance-instrument-structuredproduct.rst
- docs/2.8.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-structuredproduct.rst
- docs/2.8.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/873
> Document Barrier Reverse Convertible

- docs/2.7.0/docs/daml-finance/concepts/lifecycling.rst
- docs/2.8.0/docs/daml-finance/concepts/lifecycling.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1008
> Update links to time/election based lifecycling

- docs/2.8.0/docs/daml-finance/tutorials/lifecycling/fixed-rate-bond.rst
- docs/2.8.0/docs/daml-finance/tutorials/lifecycling/floating-rate-bond.rst
Fixes https://github.com/digital-asset/daml-finance/issues/484
> Document app time management for lifecycling

- docs/2.7.0/docs/daml-finance/instruments/option.rst
- docs/2.8.0/docs/daml-finance/instruments/option.rst
Fixes https://github.com/digital-asset/daml-finance/issues/977
> Rearrange option tutorial

- docs/2.8.0/docs/daml-finance/index.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1015
> Link to the forum

- docs/2.8.0/docs/daml-finance/instruments/generic.rst
- docs/2.8.0/docs/daml-finance/instruments/token.rst
Fixes https://github.com/digital-asset/daml-finance/issues/196
> Ensure that all instrument tutorials have an FAQ section

- docs/2.8.0/docs/daml-finance/index.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1029
> Explain distribution and download of Daml Finance

- docs/2.8.0/docs/daml-finance/instruments/bond.rst
- docs/2.8.0/docs/daml-finance/packages/implementations/daml-finance-util.rst
- docs/2.8.0/docs/daml-finance/packages/interfaces/daml-finance-interface-types-date.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1017
> Improve documentation of date utility packages

- docs/2.8.0/docs/daml-finance/tutorials/advanced-topics/instrument-modeling/contingent-claims-instrument.rst
- docs/2.8.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/1016
> Improve custom instrument tutorial

- docs/2.8.0/docs/daml-finance/reference/patterns.rst
This addresses the comments made in #450
> improve description of Reference pattern

- docs/2.8.0/docs/daml-finance/concepts/lifecycling.rst
- docs/2.8.0/docs/daml-finance/instruments/generic/contingent-claims.rst
- docs/2.8.0/docs/daml-finance/packages/implementations/daml-finance-data.rst
- docs/2.8.0/docs/daml-finance/reference/glossary.rst
- docs/2.8.0/docs/daml-finance/tutorials/advanced-topics/instrument-modeling/contingent-claims-instrument.rst
- docs/2.8.0/docs/daml-finance/tutorials/payoff-modeling/basic-builders.rst
- docs/2.8.0/docs/daml-finance/tutorials/payoff-modeling/intro.rst
- docs/2.8.0/docs/daml-finance/tutorials/payoff-modeling/observations.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1054
> Modify use of cashflow in the docs

- docs/2.8.0/_toc.yml
- docs/2.8.0/docs/daml-finance/instruments/bond.rst
- docs/2.8.0/docs/daml-finance/instruments/swap.rst
- docs/2.8.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-bond.rst
- docs/2.8.0/docs/daml-finance/packages/interfaces/daml-finance-interface-instrument-types.rst
- docs/2.8.0/docs/daml-finance/packages/interfaces/daml-finance-interface-types-date.rst
- docs/2.8.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/1061
Fixes https://github.com/digital-asset/daml-finance/issues/1058
> Update docs after adding SOFR index support

- docs/2.8.0/docs/daml-finance/tutorials/advanced-topics/instrument-modeling/date-utilities.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1074
> Add summary and next steps

- docs/2.8.0/docs/daml-finance/instruments/bond.rst
Fixes https://github.com/digital-asset/daml-finance/issues/1073
> Clarify that TIPS inflation linked bonds are supported

- docs/2.8.0/docs/canton/usermanual/performance.rst
- docs/2.8.0/docs/canton/usermanual/persistence.rst
- docs/2.8.0/docs/canton/usermanual/troubleshooting_guide.rst
I've tried to sum up some of the lessons learned from some tuning exercises.
> Documented some performance tuning lessons.

- docs/2.6.5/.envrc
- docs/2.6.5/bin/setup-python
- docs/2.7.3/.envrc
- docs/2.7.3/bin/setup-python
- docs/2.8.0/.envrc
- docs/2.8.0/bin/setup-python
Specifically, if Python is already set up, don't reinstall it from scratch every time one `cd`'s into the folder.
> simplify Python install

- bin/publish-snapshots
Daml version is no longer tied to SDK version.
> fix snapshots for assembly change

- docs/2.7.4/docs/canton/reference/error_codes.rst
- docs/2.8.0/docs/canton/reference/error_codes.rst
Reported by `felix1337` [on the forum](https://discuss.daml.com/t/all-error-categories/6888?u=gary_verhaegen).
> error_code: fix inventory link

- docs/2.8.0/docs/canton/usermanual/manage_domain_entities.rst
Addresses: https://github.com/DACH-NY/canton/issues/14586
Followup from https://github.com/DACH-NY/canton/pull/14194 and https://github.com/DACH-NY/canton/issues/13609
> Document sequencer tombstones

- docs/2.8.0/_toc.yml
- docs/2.8.0/docs/daml/patterns.rst
- docs/2.8.0/docs/daml/patterns/initaccept.rst
When describing the pattern, change it from "initiate/accept" to "propose/accept".
> change "initiate" to "propose"

- bin/publish-snapshots
See https://github.com/digital-asset/daml/pull/17730.
> skip broken snapshot

- docs/2.8.0/_toc.yml
- docs/2.8.0/docs/kubernetes/06-advanced-topics/high-availability.rst
Summary of changes:
* Added a new page that describes how we achieve HA on a Kubernetes deployment for Daml Enterprise components.
> Added page on how we ensure high availability on Kubernetes [PLEN-503]

- docs/2.8.0/versions.json
mostly to get digital-asset/daml#17704
> bump daml & canton

- docs/2.8.0/_toc.yml
- docs/2.8.0/docs/daml-finance/instruments/swap.rst
- docs/2.8.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/1131
> Update asset swap docs with dividend passthrough and basket support

- docs/2.8.0/docs/canton/exts/canton_enterprise_only.py
- docs/3.0.0/docs/canton/exts/canton_enterprise_only.py
Change the wording of the disclaimer used throughout the docs about requiring a Daml Enterprise license.
> edit Daml Enterprise disclaimer

- docs/2.8.0/docs/query/pqs-user-guide.rst
- docs/2.9.0/docs/query/pqs-user-guide.rst
Update the supported postgres versions
> Update the supported postgres versions

- docs/2.9.0/_toc.yml
- docs/2.9.0/docs/app-dev/explicit-contract-disclosure.rst
- docs/2.9.0/docs/app-dev/services.rst
- Update ToC
- Add core ECD doc 
- Add ECD to services.rst 
see also https://github.com/digital-asset/docs.daml.com/pull/521/
> Add explicit contract disclosure docs to 2.9.0 from 3.0.0

- .circleci/config.yml
- docs/2.6.5/README.md
- docs/2.7.6/README.md
- docs/2.8.0/README.md
- docs/2.9.0/README.md
- docs/3.0.0/README.md
- docs/draft/.envrc
- docs/draft/.gitignore
- docs/draft/README.md
- docs/draft/_toc.yml
- docs/draft/bin/build
- docs/draft/bin/bump
- docs/draft/bin/canton/snippet_directive.py
- docs/draft/bin/canton/test_snippet_directive.py
- docs/draft/bin/clean
- docs/draft/bin/deps
- docs/draft/bin/download
- docs/draft/bin/live-preview
- docs/draft/bin/setup-python
- docs/draft/bin/setup-sphinx-source-tree
- docs/draft/bin/update-nixpkgs
- docs/draft/docs/canton/exts/canton_enterprise_only.py
- docs/draft/docs/draft.rst
- docs/draft/docs/index.rst
- docs/draft/nix/nixpkgs.nix
- docs/draft/nix/src.json
- docs/draft/requirements.txt
- docs/draft/shell.nix
- docs/draft/versions.json
This started as a copy of the 2.9.0 folder, from which I've removed all the content. This required a bit of editing in the `build` and `setup-sphinx-source-tree` scripts.
The most important aspect to review, though, is the `.circleci/config.yml` file.
> add draft site

- CODEOWNERS
This is not a coup - it's actually been discussed.
> add myself to codeowners

- docs/2.9.0/docs/canton/usermanual/installation.rst
The Config Directory Contents section is 2.8.1+
Original update: https://github.com/digital-asset/docs.daml.com/pull/583
> Add version disclaimer

- docs/2.9.0/docs/canton/includes/snippet_data/tutorials/getting_started.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/connectivity.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/identity_management.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/manage_domain_entities.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/manage_domains.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/upgrading.json
- docs/2.9.0/docs/canton/usermanual/downloading.rst
- docs/2.9.0/docs/canton/usermanual/identity_management.rst
Before this change, the repair commands had a slightly bad UX and were not very safe. Now, they have additional checks implemented, making them safer to use. At the same time, I've restructured party migration and party on multiple nodes to be covered using just one guide.
> Updated repair commands

- docs/2.8.0/docs/canton/includes/snippet_data/tutorials/getting_started.json
- docs/2.8.0/docs/canton/includes/snippet_data/usermanual/connectivity.json
- docs/2.8.0/docs/canton/includes/snippet_data/usermanual/identity_management.json
- docs/2.8.0/docs/canton/includes/snippet_data/usermanual/manage_domain_entities.json
- docs/2.8.0/docs/canton/includes/snippet_data/usermanual/manage_domains.json
- docs/2.8.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json
- docs/2.8.0/docs/canton/includes/snippet_data/usermanual/upgrading.json
- docs/2.8.0/docs/canton/usermanual/downloading.rst
- docs/2.8.0/docs/canton/usermanual/identity_management.rst
- docs/2.9.0/docs/canton/usermanual/identity_management.rst
Backported the following functionality to 2.8
https://github.com/digital-asset/docs.daml.com/pull/618
https://github.com/digital-asset/docs.daml.com/pull/597
> Backported party migration macro improvements to 2.8.1

- docs/2.9.0/docs/daml-finance/concepts/settlement.rst
FIXES https://github.com/digital-asset/daml-finance/issues/1201
> Daml Finance: Adding settlement-time section

- .circleci/config.yml
Mostly to say we have one; this is the default behaviour.
> add robots.txt

- docs/2.9.0/docs/canton/usermanual/identity_management.rst
Goes with https://github.com/DACH-NY/canton/pull/16979
> Add offboarded parties to repair.party_migration.step6_cleanup_source (2.9)

- docs/2.8.1/docs/daml/reference/structure.rst
- docs/2.9.0/docs/daml/reference/structure.rst
- docs/2.9.0/docs/daml/reference/templates.rst
Part of https://github.com/digital-asset/daml/issues/18414
Daml PR: https://github.com/digital-asset/daml/pull/18468
GHC PR: https://github.com/digital-asset/ghc/pull/179
docs.daml.com PR: https://github.com/digital-asset/docs.daml.com/pull/640
> Document template agreement deprecation

- docs/2.7.7/docs/query/pqs-user-guide.rst
- docs/2.8.1/docs/query/pqs-user-guide.rst
- docs/2.9.0/docs/query/pqs-user-guide.rst
We've had multiple reports of people unable to find this information, so I suggest adding it in an easy-to-find place.
> add Docker image to pqs docs

- docs/2.9.0/docs/canton/usermanual/pruning.rst
Backporting new Schedule format section from 3.0.0 -- see also #556
> Add Schedule format

- docs/2.7.9/docs/canton/usermanual/console.rst
- docs/2.8.3/docs/canton/usermanual/console.rst
- docs/2.9.0/docs/canton/usermanual/console.rst
- docs/3.1/docs/canton/usermanual/console.rst
This section has never been clear to me. I've made what I believe are clarifying edits.
> Correct errors and make clarifying edits for remote administration

- docs/3.1/_toc.yml
- docs/3.1/docs/app-dev/explicit-contract-disclosure.rst
> Make explicit disclosure GA

- docs/2.7.9/docs/query/pqs-user-guide.rst
- docs/2.8.4/docs/query/pqs-user-guide.rst
- docs/2.9.0/docs/query/pqs-user-guide.rst
- docs/3.1/docs/query/pqs-user-guide.rst
Add docs on the pqs scribe params  `--pipeline-ledger-stop` and  `--pipeline-datasource`
> update docs on streaming option enum values in pqs scribe

- docs/2.7.9/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/domain.rst
- docs/2.8.5/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/domain.rst
- docs/2.9.0/docs/deploy-daml/infrastructure-architecture/high-availability/basic-ha/domain.rst
* the domain does not return 'sequenced endpoints'
* the domain is not the ledger
> Improve sentence in HA section

- nix/src.json
This should not have any negative effect on the Sphinx build.
> Bump nix packages

- docs/2.9.0/docs/canton/includes/snippet_data/tutorials/getting_started.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/connectivity.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/identity_management.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/manage_domain_entities.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/manage_domains.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json
- docs/2.9.0/docs/canton/includes/snippet_data/usermanual/upgrading.json
- docs/2.9.0/docs/canton/usermanual/upgrading.rst
Documentation for https://github.com/DACH-NY/canton/issues/18541
> One step migration

- docs/2.9.0/_toc.yml
- docs/2.9.0/docs/daml-finance/instruments/structured-product.rst
- docs/2.9.0/versions.json
Fixes https://github.com/digital-asset/daml-finance/issues/1217
> Remove auto-callable from v2.9 docs

- docs/2.10.0/docs/canton/usermanual/apis.rst
- docs/2.8.7/docs/canton/usermanual/apis.rst
- docs/2.9.0/docs/canton/usermanual/apis.rst
- docs/3.1/docs/canton/usermanual/apis.rst
Addresses [#18640](https://github.com/DACH-NY/canton/issues/18640).
> Explain Client and Server Auth on domain public API

- docs/3.1/docs/canton/exts/pygments_daml_lexer.py
- docs/3.1/docs/concepts/glossary.rst
- docs/3.1/docs/concepts/ledger-model/ledger-daml.rst
- docs/3.1/docs/concepts/ledger-model/ledger-integrity.rst
- docs/3.1/docs/concepts/ledger-model/ledger-structure.rst
- docs/3.1/docs/daml/reference/structure.rst
- docs/3.1/docs/daml/reference/templates.rst
- docs/3.1/docs/daml/troubleshooting.rst
- docs/3.1/docs/tools/navigator/index.rst
Removal of non-ledger API-related agreement text occurrences (in 3.1).
> [canton-15209] Remove agreement text from 3.x

- docs/2.10.0/docs/canton/usermanual/monitoring.rst
- docs/2.10.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/ha-in-the-cloud.rst
- docs/2.8.7/docs/canton/usermanual/monitoring.rst
- docs/2.9.0/docs/canton/usermanual/monitoring.rst
- docs/2.9.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/ha-in-the-cloud.rst
- docs/3.1/docs/canton/usermanual/monitoring.rst
- docs/3.1/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/ha-in-the-cloud.rst
Formerly Common Metrics, now Monitoring. Plus grammar touch-ups.
Resolves #727
> Fix links to monitoring

- theme/build.sh
I think this fixes the missing CSS file.
> fix docs theme build

- docs/2.10.0/docs/tools/assistant.rst
- docs/2.9.3/docs/tools/assistant.rst
- docs/3.1/docs/tools/assistant.rst
Intended to do this in the last PR, but merged by accident :(
> Update env var notes to capture Curtis' release notes

- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
Upgrade limitation was fixed, removing from docs.
> Remove fixed limitation

- docs/2.10.0/docs/canton/usermanual/pruning.rst
- docs/2.7.9/docs/canton/usermanual/pruning.rst
- docs/2.8.10/docs/canton/usermanual/pruning.rst
- docs/2.9.4/docs/canton/usermanual/pruning.rst
For technical details, please refer to
https://support.digitalasset.com/s/case/500Pq00000NCXEIIA5/ledger-pruning-unexpected-behavior
> Document participant pruning restriction per support-7725

- docs/2.10.0/docs/canton/usermanual/upgrading.rst
- docs/2.9.4/docs/canton/usermanual/upgrading.rst
Related to Canton issue https://github.com/DACH-NY/canton/pull/21875
> i21875: Clarify usage of flag for unauthenticated contract IDs

- docs/2.10.0/bin/build
- docs/2.3.20/docs/build.sh
- docs/2.7.9/bin/build
- docs/2.8.10/bin/build
- docs/2.9.5/bin/build
- docs/3.1/bin/build
Originally, I planned to remove the duplicated lines, but it turned out they were actually needed: https://github.com/digital-asset/docs.daml.com/pull/825.
The second best thing to do is to add comments with explanations.
Previous PR: https://github.com/digital-asset/docs.daml.com/pull/826
> Add comments for double lualatex commands

- docs/2.9.5/_toc.yml
- docs/2.9.5/docs/canton/usermanual/connectivity.rst
- docs/2.9.5/docs/canton/usermanual/decommissioning.rst
- docs/2.9.5/versions.json
> Add 2.9.5 decommissioning docs

- docs/2.10.0/docs/canton/usermanual/persistence.rst
- docs/2.10.0/docs/canton/usermanual/upgrading.rst
- docs/2.9.5/docs/canton/usermanual/persistence.rst
- docs/2.9.5/docs/canton/usermanual/upgrading.rst
Once approved, I'll add to 2.10, 2.8 and 3.x
> Improve upgrade documentation

- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
Update daml-script-beta to daml-script-lts. Remove references to beta
> Daml script tweaks

- docs/2.10.0/docs/daml/intro/9_Dependencies.rst
I was looking for the docs at the wrong place, so figured it's worth pointing to the multi-package build. Thought the whole section could use some refreshing.
> Added a small section to point to the multi-package build

- docs/2.10.0/docs/concepts/ledger-model/upgrade-model-in-depth.rst
- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
> document that the upgrade check allows for removing observers that are also signatories

- docs/2.10.0/docs/app-dev/bindings-java/quickstart.rst
- docs/2.10.0/docs/daml/intro/9_Dependencies.rst
- docs/2.10.0/versions.json
The 2.10.0 release happens soonish, so it's worthwhile to bump these dependencies.
> Bump 2.10.0 doc dependencies

- CODEOWNERS
This reverts commit 0deb42debcb79d87543bd998c1438e24078367d5.
> Revert "Request PR reviews for docs content only from the docs team

- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
Reorganize to the following after discussion w/in language team
```
- Overview (was: theory of operation)
- The Programming Model by Example
- Package Selection in the Ledger API (was: Ledger API - under components)
- Migrating to SCU
- Best Practices
- Testing
- SCU Support in Daml Tooling
- Codegen
- JSON API Server
- PQS
- Daml Shell 
- Daml-Script
- Daml Studio support
```
> Reorganize SCU sections

- docs/2.10.0/docs/daml/reference/packages.rst
- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
- [aead2b8](https://github.com/digital-asset/docs.daml.com/pull/874/commits/aead2b8955240aefa14620a9c241f4d66ab385e5): UPD 27, module prefixes.
- [a03a60a](https://github.com/digital-asset/docs.daml.com/pull/874/commits/a03a60aeb77b1f70e850d92a004be2bdc0167753): UPD 15 to the best of my ability, verify limitations
- [8bf9deb](https://github.com/digital-asset/docs.daml.com/pull/874/commits/8bf9debe9e397a22e480c04ebb89e74c56855e3d): UPD 22, daml script testing recommendation
- [b3c49a6](https://github.com/digital-asset/docs.daml.com/pull/874/commits/b3c49a61edd01265d7641f1140eb3e235676c5fd): Additional point about interface instance changes, related to UPD 15
To be merged after https://github.com/digital-asset/docs.daml.com/pull/871
> Handle UPD 15,22,27

- docs/2.10.0/docs/canton/usermanual/upgrading.rst
Incorporate @carrielaben-da corrections for the 2.10 upgrading article
> Reformulate the 2.10 upgrading guide

- docs/2.10.0/docs/tools/assistant-build.rst
- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
> document developer workflow

- docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
This PR:
- Makes the story around package preferences and Ledger API package selection more coherent and complete.
- Introduces `Operational Design Guideline for Upgrading Daml Apps` in `Best practices`
> Add Operational Design guidelines for Upgrading Daml Apps section

- docs/2.8.11/docs/canton/usermanual/security.rst
Contributes to https://github.com/DACH-NY/canton/issues/23581
> Add warning about rolling sequencer keys with disabled participants

- docs/2.10.0/docs/concepts/ledger-model/upgrade-model-in-depth.rst
Fixes https://github.com/DACH-NY/canton/issues/23367#issue-2780114442.
> Document value validation and normalization in the ledger API

- docs/3.1/docs/tsa-arch/daml-app-arch-design.rst
I noticed that I should've provided the link to a relevant resource, which covers a different aspect of the main topic.
> Intro added to provide context and extra resource

- docs/2.10.2/docs/query/pqs-user-guide.rst
This PR clarifies stable ordering of events in PQS and provides an example how deterministic pagination of events may be implemented.
> PQS: clarify stable ordering of events
