LATEST, docs/setup-sphinx-source-tree.sh
Bumps Canton for 2.1.1 release, and fixes the Scaladoc links as in https://docs.daml.com/2.1.1/canton/usermanual/static_conf.html#configuration-reference linking to https://docs.daml.com/2.2.0-snapshot.20220412.9721.0.b7c4bdab/canton/scaladoc/com/digitalasset/canton/config/index.html (wrong version number, using the daml version instead of the docs version).
=> fix scaladoc links

.circleci/config.yml
I wasn't quite sure how to pick the finance version; this seems adequate if we assume we always build snapshots reasonably on time.
=> fix snapshot upload

docs/index/deploy-daml/intro/index.rst, docs/index/operate-a-daml-ledger/advanced-operations/index.rst, docs/index/operate-a-daml-ledger/common-tasks/index.rst
The Operational Processes page has been split; this updates the TOC to reflect that.
=> Removing the Operational Processes links

LATEST, README.md
- Upgrade Daml Finance version to 0.1.7
- Remove redundant instruction from "How to build locally"
=> Upgrade to daml finance assembly 0.1.7

docs/index/create-daml-apps/intro/index.rst, docs/index/create-daml-apps/standard-library/index.rst, docs/index/index.rst
And adding a place for the new introduction page when it is approved.
[CHANGELOG_END}
=> Restoring the Write Smart Contracts With Daml structure

README.md, docs/.gitignore, docs/index/index.rst
- Moving the Finance TOC to underneath the Canton docs.
- Adding an entry to gitignore for the html folder.
- Requesting tech review from @garyverhaegen-da and architecture review from @digital-asset/daml-docs
=> Move finance toc

LATEST, docs/index/index.rst
```
deps use 2.5.0-rc1
2.5.0-snapshot.20221201.11065.0.caac1d10 2.5.0-rc1 caac1d10109749e9ef9dbcdd09150818311fcd9f
```
See [LATEST in assembly](https://github.com/DACH-NY/assembly/blob/main/LATEST), which points to canton version `2.5.0-rc1`  and daml snapshot `2.5.0-snapshot.20221201.11065.0.caac1d10`.
=> Updated LATEST to rc1 snapshots.

_toc.yml
It's easy to make mistakes with the TOC. I had moved the top level toc entry but with nothing underneath it, without noticing. Fixed.
=> fixing toc issues design patterns

.circleci/config.yml
Turns out, beyond the credentials issue, there was actually also a small bug introduced by #104, in that I forgot to update the path for the workdir folder in the cron code.
This should fix that.
=> fix workdir path in snapshot release

docs/2.5.2/LATEST
This is a special snapshot I have created to include [this PR](https://github.com/digital-asset/daml/pull/16188), which itself is a backport of @da-katmurp's [PR](https://github.com/digital-asset/daml/pull/16077).
This is demonstrating that we can update a published daml version, including the one currently displayed on root, after the release of that version (as long as we manually create corresponding snapshots).
=> remove mopinion from 2.5.2

docs/2.5.3/docs/app-dev/bindings-ts/index.rst, docs/2.5.3/docs/setup-sphinx-source-tree.sh
This aims at fixing the missing link on https://docs.daml.com/app-dev/bindings-ts/. https://github.com/digital-asset/daml/pull/16315 fixed it on 2.6.0, but that's still some time away so let's get it fixed on root too.
=> backport bindings-ts fix

docs/2.6.0/docs/app-dev/bindings-ts/index.rst
Felt a bit weird to have done it for 2.5.3 and not for 2.6.0.
=> add bindings-ts/index to 2.6.0

docs/2.6.0/docs/tools/trigger-service/index.rst, docs/2.7.0/docs/tools/trigger-service/index.rst
I found during testing related to support ticket [00003571](https://digitalasset1.lightning.force.com/lightning/r/Case/5004x00000LbSWXAA3/view), that the only necessary configuration option to define in the configuration file for the trigger service is the ledger-api section.
Created originally in the daml repo: https://github.com/digital-asset/daml/pull/15635
CHANGELOG_BEGIN
CHANGELOG_END
=> Mandatory config options in trigger service docs

docs/2.6.0/_toc.yml, docs/2.6.0/versions.json, docs/2.7.0/_toc.yml, docs/2.7.0/versions.json
This finalises the migration of the Daml Finance docs to this repo: the `1.1.4` assembly package includes only the code snippets and auto-generated documentation
=> Update Daml Finance to 1.1.4

docs/2.6.0/docs/daml/reference/interfaces.rst, docs/2.7.0/docs/daml/reference/interfaces.rst
Requires is now enabled by default so the warning for 1.dev does not apply any more.
=> Requires is now enabled by default

docs/2.6.0/docs/ops/common-metrics.rst, docs/2.7.0/docs/ops/common-metrics.rst
* values in `service` label uses `_`, not `-`
* the paths usually start with a version segment
=> Fixes small details in common metrics

docs/2.6.0/docs/daml/reference/contract-keys.rst, docs/2.6.0/docs/daml/reference/updates.rst, docs/2.7.0/docs/daml/reference/contract-keys.rst, docs/2.7.0/docs/daml/reference/updates.rst
the explanations in "Reference: Contract Keys" seem correct and generally clearer to me. Keeping a single source of truth will also prevent conflicting docs in the future.
=> Updates ref docs for `*ByKey` functions now point to Contract Keys ref docs

docs/2.3.10/docs/index/index_html.rst, docs/2.3.10/docs/index/index_pdf.rst, docs/2.3.8/docs/index/index_html.rst, docs/2.3.8/docs/index/index_pdf.rst, docs/2.3.9/docs/index/index_html.rst, docs/2.3.9/docs/index/index_pdf.rst, docs/2.4.3/docs/index/_toc.yml, docs/2.4.3/docs/index/index.rst, docs/2.4.3/docs/index/index_html.rst, docs/2.4.3/docs/index/index_pdf.rst, docs/2.5.1/docs/index/_toc.yml, docs/2.5.1/docs/index/index.rst, docs/2.5.2/docs/index/_toc.yml, docs/2.5.2/docs/index/index.rst, docs/2.5.3/docs/index/_toc.yml, docs/2.5.3/docs/index/index.rst, docs/2.5.5/docs/index/_toc.yml, docs/2.5.5/docs/index/index.rst, docs/2.6.0/docs/app-dev/bindings-java/quickstart.rst, docs/2.7.0/docs/app-dev/bindings-java/quickstart.rst
This reverts commit 5bb797397999fa184c4687720b1d97023409e10f.
The link is no longer dead.
=> Revert "remove links to deleted examples page (#209)"

docs/2.6.0/bin/build, docs/2.7.0/bin/build
The Hoogle servers check for a new version of `https://docs.daml.com/hoogle_db.tar.gz` every five minutes, so if everything goes as planned the finance code should be searchable on `https://hoogle.daml.com` within about an hour of merging this.
=> add finance to hoogle db

docs/2.6.4/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/implementing-ha.rst, docs/2.7.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/implementing-ha.rst
Unfortunately there's no label for the second link to point to on the Canton side, so I've made it work for now but it's likely to break again in the future.
(Or, rather, should it break in the future it will be a silent failure.)
=> fix 2 links

bin/publish-snapshots
The canton side of the docs is broken in (at least) two ways for this release:
1. There's a path issue with the literalinclude of Identifier.scala, which could be resolved by modifying setup-sphinx-source-tree.
2. There's a reference to a missing config file, which we can't really solve on this side of things.
=> skip broken snapshot

docs/2.6.4/docs/daml-finance/tutorials/getting-started/intro.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/intro.rst
The libs used for codegen are no longer versioned -- correct in the docs
Fixes https://github.com/digital-asset/daml-finance/issues/841
=> correct js and java codegen daml finance for 2.6.4 and 2.7.0

docs/2.0.1/docs/overwrite/canton/usermanual/installation.rst, docs/2.1.1/docs/overwrite/canton/usermanual/installation.rst, docs/2.2.0/docs/overwrite/canton/usermanual/installation.rst, docs/2.4.3/docs/overwrite/canton/usermanual/installation.rst, docs/2.5.5/docs/canton/usermanual/installation.rst, docs/2.6.4/docs/canton/usermanual/installation.rst
Note: we cannot fix 2.3.12 with the current infrastructure as it uses a `snippet` directive of the Canton preprocessor.
=> fix canton install instructions

docs/2.7.0/docs/daml-finance/tutorials/getting-started/holding.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/transfer.rst
Now that we have a dedicated `Holding` script for the holding tutorial, we need to move the step-by-step instructions to the Holding tutorial (since this comes first).
=> Move sample code step-by-step instructions to the Holding tutorial

docs/2.7.0/docs/daml-finance/overview/building-applications.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/intro.rst
- fix typo
- move section explaining how to run the codegen from "getting started" to "building applications"
- replace URL link with `:doc:` link
For @digital-asset/daml-docs fyi, the [codegen page](https://docs.daml.com/tools/codegen.html)
- is disconnected from example explaining how to use the tool, such as [here](https://docs.daml.com/app-dev/bindings-ts/daml2js.html) and [here](https://docs.daml.com/app-dev/bindings-java/index.html)
- references a GH issue that has been closed 2.5 years ago
=> Move daml finance codegen section

.circleci/config.yml
The dropdown defaults to the first entry on the root site, so I'm putting the dev site as the second entry.
=> fix dev dropdown

.circleci/config.yml
The daml assistant (`daml` cli utility) depends on the `versions.json` file (it really shouldn't, but here we are). This means that it now reports `2.7.0` as the latest available version, and that's bad as that doesn't exist yet.
It also means we can't currently do smart things for the docs like having versions per minor instead of per patch (i.e. `docs/2.6` instead of `docs/2.6.4` that we need to rename when a 2.6.5 comes out).
We clearly do want a version of the dropdown that includes the dev preview, but the current solution is not working out. I'm disabling it temporarily and will be looking into finding a better one over the next couple days.
=> temporarily remove dev from dropdown

docs/2.7.0/docs/app-dev/authorization.rst, docs/2.7.0/docs/canton/architecture/domains/domains.rst, docs/2.7.0/docs/canton/usermanual/ha.rst, docs/2.7.0/docs/concepts/test-evidence.rst, docs/2.7.0/docs/daml-finance/overview/extending-daml-finance.rst
No further unwanted Canton.io links were found, but while checking I ran across some typos that needed cleaning up.
=> Typo fixes

docs/2.7.0/bin/live-preview, docs/2.7.0/docs/canton/architecture/domains/domains.rst, docs/2.7.0/docs/canton/exts/snippets.py, docs/2.7.0/docs/canton/usermanual/domains/domains.rst
Tested:
- Changing text in `canton/tutorials/getting_started.rst` updates as expected.
- Changing a title in `canton/tutorials/getting_started.rst` updates the title in the toc on the left.
- Changing a title in `_toc.yml` refreshes the page and updates the toc on the left with `http://localhost:8000/canton/tutorials/getting_started.html` open.
As far as I can tell it's all working as expected, but I'm not working with `live-preview` much so please report any further issue.
=> fix live-preview for canton

docs/2.6.5/bin/build, docs/2.7.0/bin/build
This fixes #336. The issue lies in the javadoc produced by the daml repo, but I don't know how to fix it over there, because Bazel. This is an ugly workaround, but it works for now.
Thanks to @wallacekelly-da for reporting.
=> fix javadoc search

docs/2.7.0/_toc.yml
Since the title of the explicit contract disclosure page changed, update the TOC text to match it.
=> match toc for explicit disclosure page

docs/2.7.0/docs/canton/usermanual/monitoring/etc/network-docker-compose.yml
When running the monitoring example with `./dc.sh up -d` then the error `network monitoring declared as external, but could not be found` is reported.
This change defines the "monitoring network" as non-external which prevents this error.
Using `external: true` was helpful during the development only, so that docker-compose could be run many times, and adding new nodes to the network.
=> Fix unnecessary warning when starting the monitoring

docs/2.7.0/docs/canton/architecture/requirements/requirements.rst
After fixing the canton todo checker, this todo will be reported and blocks PR merges on the canton repository. Because the related issue has been closed for sometime this todo is simply removed.
Relates to [canton issue 13862](https://github.com/DACH-NY/canton/pull/13862)
=> Remove todo for issue 156

docs/2.7.0/docs/canton/usermanual/security.rst
Updated the required permissions for AWS KMS usage and added a note on cross-account key usage.
=> Clarify KMS permissions

docs/2.7.0/docs/daml-finance/overview/intro.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/intro.rst
I moved the reference to the [Daml Finance Reference App](https://github.com/digital-asset/daml-finance-app) to the main `intro` section.
It was previously sitting in the intro to the getting started tutorials.
I feel that the previous placement positioned the `Reference App` as a graphical-based alternative to the getting started scripts. However, it should not be the case as the Reference App is not documented to a sufficient extent.
Happy to know what you think
=> Move Reference App section

docs/2.7.0/docs/canton/usermanual/apis.rst, docs/2.7.0/docs/canton/usermanual/identity_management.rst, docs/2.7.0/docs/tools/sandbox.rst, docs/2.8.0/docs/canton/usermanual/apis.rst, docs/2.8.0/docs/canton/usermanual/identity_management.rst, docs/2.8.0/docs/tools/sandbox.rst
A little rationalization of where the information is located. We prefer general information applicable to all platforms to be in the user manual where everyone can find it. It's not so great when it is located in sandbox where it may seem like only applicable to that tool.
- moved jwt config documentation from sandbox to user manual's api section
- moved additional admin documentation from sandbox to user manual's identity management section
=> Move jwt documentation to user manual

docs/2.7.0/_toc.yml, docs/2.7.0/docs/daml-finance/concepts/asset-model.rst, docs/2.7.0/docs/daml-finance/reference/patterns.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/holdings.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/intro.rst, docs/2.7.0/docs/daml-finance/tutorials/getting-started/transfer.rst, docs/2.7.0/docs/daml-finance/tutorials/lifecycling/fixed-rate-bond.rst
Fixes https://github.com/digital-asset/daml-finance/issues/937
- rename `Holding` tutorial to `Holdings`
- move pre-requisite section to getting-started intro
- move section outlining structure of the project to getting-started intro
- simplify description of holding tutorial
- fix code snippet rendering
=> Restructuring of holdings tutorial

docs/2.3.15/.gitignore, docs/2.3.15/docs/overwrite/canton/architecture/domains/domains.rst, docs/2.4.3/.gitignore, docs/2.4.3/docs/overwrite/canton/architecture/domains/domains.rst, docs/2.5.5/docs/canton/architecture/domains/domains.rst, docs/2.6.5/docs/canton/architecture/domains/domains.rst
Advice for reviewers: this PR is separated into three commits. The first one is just tweaking `.gitignore` files and can be mostly ignored. The second one just copies the relevant Canton files to this repo, so there's a lot of added text. This is a straight up copy from the Canton tarball, with no change. Finally, the last commit, which should be the only one with an impact on the live website, removes the offending sections from the four "imported" files.
=> Remove tps

docs/2.7.0/docs/canton/tutorials/getting_started.rst, docs/2.8.0/docs/canton/tutorials/getting_started.rst
Instead of always relying on `bin/canton` to start Canton, we now also document to start Canton via `java` in the getting started guide.
=> Documented to start Canton via java directly

docs/2.8.0/docs/canton/architecture/security.rst, docs/2.8.0/docs/canton/usermanual/security.rst, docs/2.8.0/versions.json
After all the new docs we added for KMS the version 2.7.0 and 2.8.0 did not match anymore. I merged all changes in 2.7.0 to 2.8.0.
=> Update docs 2.8.0 to match 2.7.0

bin/publish-snapshots
The job fails on canton's 2.8.0-snapshot.20230808.10971.0.v886a4311 tarball because it misses two include files which are required.
The updated tarball, stated in the versions.json, 2.8.0-snapshot.20230809.10977.0.vf08ea807 fixes this problem.
The broken tarball version has been added to broken list of the publish-snapshots script.
Example failing job:
https://app.circleci.com/pipelines/github/digital-asset/docs.daml.com/13404/workflows/b6438a73-5757-4ca9-a334-26c40e03859e/jobs/13841
=> Fix failing publish-snapshots job for canton 2.8.0 tarball

docs.daml.com.iml, docs/2.7.0/docs/tools/trigger-service/index.rst, docs/2.8.0/docs/tools/trigger-service/index.rst
=> For 2.7 and 2.8: add in trigger service ledger API client TLS configuration documentation

docs/2.5.5/docs/index/_toc.yml, docs/2.5.5/docs/index/operate-a-daml-ledger/common-tasks/index.rst, docs/2.6.5/_toc.yml, docs/2.7.0/_toc.yml, docs/2.8.0/_toc.yml
Somebody previously renamed the section "Repair Nodes" to Repair Topology Information despite the fact that the section actually covers the repair service, which isn't about repairing topology, but repairing the contract state. This PR now reverts this change.
=> Changed repair section back to repair nodes

docs/2.7.1/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst, docs/2.8.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst
Fixed the links to Deploying a Generic Ledger and Monitoring in the HA Use Cases page.
=> Generic ledger links

docs/2.7.1/docs/canton/usermanual/performance.rst, docs/2.8.0/docs/canton/usermanual/performance.rst
The existing recommendation contradicted how we recommend customers deploy Canton.
=> Remove contradictory info

docs/2.6.5/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst, docs/2.7.1/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst, docs/2.8.0/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst
Similar to #460 but includes 2.6.5 (before that the issue is _probably_ present but the source is in Canton repo), and changing the URL format from external to internal so the vailidity of the link gets checked by Sphinx at build time. (So if we move these files around in the future we'll be notified that the links have broken.)
=> fix deploy links

docs/2.8.0/versions.json
daml: 2.8.0-snapshot.20230919
canton: 2.8.0-snapshot.20230921
=> bump daml and canton versions

docs/2.4.3/docs/overwrite/canton/usermanual/installation.rst, docs/2.5.5/docs/canton/usermanual/installation.rst, docs/2.6.5/docs/canton/usermanual/installation.rst, docs/2.7.1/docs/canton/usermanual/docker.rst, docs/2.7.1/docs/canton/usermanual/example_monitoring_setup.rst, docs/2.7.1/docs/canton/usermanual/installation.rst, docs/2.7.1/docs/canton/usermanual/monitoring/etc/postgres-docker-compose.yml, docs/2.8.0/docs/canton/usermanual/docker.rst, docs/2.8.0/docs/canton/usermanual/example_monitoring_setup.rst, docs/2.8.0/docs/canton/usermanual/installation.rst, docs/2.8.0/docs/canton/usermanual/monitoring/etc/postgres-docker-compose.yml
Since Canton and PQS both support postgres 14, update to this newer version in the examples and docs
=> update from postgres 11 to postgres 14 in docker instructions

docs/2.8.0/docs/canton/usermanual/apis.rst, docs/2.8.0/versions.json
Document the parameters governing the sizing of the ledger api caches and the in-memory fan-out
=> Document cache sizes and imfo size

docs/2.7.4/docs/canton/usermanual/upgrading.rst, docs/2.8.0/docs/canton/usermanual/upgrading.rst
Before this change, we didn't point out to users that they should vaccuum their database before starting a node after db migration. Now, we do.
=> Documented the database vacuumn necessities.

docs/2.8.0/docs/canton/usermanual/installation.rst
To avoid out-dated information, replaces the recommendation for a specific Postgres version with a general statement and a link to find the Canton tested Postgres versions.
Also asserts that the code snippets are just there for illustrative purposes and may need to be adapted by the reader, e.g. choosing a different Postgres Docker image.
=> Update section 'Persistence using Postgres' (Canton Installation)

docs/2.8.0/docs/canton/usermanual/apis.rst
The issue triggering the mention of `libcrypt` [1] has been resolved with the issue [2] for the Canton 2.8 release.
[1] https://github.com/DACH-NY/canton/issues/11866
[2] https://github.com/DACH-NY/canton/issues/15301
=> Remove `libcrypt1` mention in the 'TLS Configuration' section

docs/2.8.0/docs/canton/includes/snippet_data/tutorials/getting_started.json, docs/2.8.0/docs/canton/includes/snippet_data/usermanual/connectivity.json, docs/2.8.0/docs/canton/includes/snippet_data/usermanual/identity_management.json, docs/2.8.0/docs/canton/includes/snippet_data/usermanual/manage_domain_entities.json, docs/2.8.0/docs/canton/includes/snippet_data/usermanual/manage_domains.json, docs/2.8.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json, docs/2.8.0/docs/canton/includes/snippet_data/usermanual/upgrading.json, docs/2.8.0/docs/canton/usermanual/identity_management.rst, docs/3.0.0/docs/canton/includes/snippet_data/tutorials/getting_started.json, docs/3.0.0/docs/canton/includes/snippet_data/usermanual/connectivity.json, docs/3.0.0/docs/canton/includes/snippet_data/usermanual/identity_management.json, docs/3.0.0/docs/canton/includes/snippet_data/usermanual/manage_domain_entities.json, docs/3.0.0/docs/canton/includes/snippet_data/usermanual/manage_domains.json, docs/3.0.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json, docs/3.0.0/docs/canton/includes/snippet_data/usermanual/upgrading.json, docs/3.0.0/docs/canton/usermanual/identity_management.rst
`PingPong` (a test Daml contract) is now only available through the Java Bindings (see https://github.com/DACH-NY/canton/pull/15189). Thus the `snippet` directives in the Canton `identity_management.rst` file need to be adapted. 
While maybe not needed, this change also regenerates the `snippet` output data using the respective Canton versions `2.8.0` and `3.0.0`.
=> Fix snippets using PingPong for 2.8.0 and 3.0.0

docs/2.8.0/docs/canton/usermanual/performance.rst, docs/3.0.0/docs/canton/usermanual/performance.rst
This feature was introduced in 2.5 but was never properly documented in the user manual
=> Document rate limiting

docs/2.8.0/_toc.yml, docs/2.8.0/docs/tools/assistant-build.rst, docs/2.8.0/docs/tools/assistant-commands.rst, docs/2.8.0/docs/tools/assistant-install.rst, docs/2.8.0/docs/tools/assistant.rst, docs/3.0.0/_toc.yml, docs/3.0.0/docs/tools/assistant-build.rst, docs/3.0.0/docs/tools/assistant-commands.rst, docs/3.0.0/docs/tools/assistant-install.rst, docs/3.0.0/docs/tools/assistant.rst
[do not review until Wednesday!!] ☃️ 
Restructure the Assistant section to accommodate some new documentation on multi-package builds (coming soon in a separate PR from @samuel-williams-da). The new content would make the page quite long and unwieldy if we were to just add it to the existing page.
* Break up the page and create new sub-pages with the existing content
* Add the new pages to the ToC
* Make a few edits to ToC entries and headings (probably more coming in a later PR after some team consultation)
=> Restructure Assistant section

docs/3.0.0/docs/canton/usermanual/manage_domains.rst
The mechanism to manipulate "dynamic domain parameters" is changing in daml 3 compared to daml 2. I have changed the code snippets embedded in `manage_domains.rst` accordingly as described in https://github.com/DACH-NY/canton/pull/15623 . This PR updates the documentation to be in sync as well.
Advances https://github.com/DACH-NY/canton/issues/15693
=> Update daml-3.x section on dynamic domain parameters

docs/2.6.5/docs/app-dev/grpc/index.rst, docs/2.7.6/docs/app-dev/grpc/index.rst
Someone who knows where this went should update the 2.8.0 and 3.0.0 sites.
=> update protobuf links (2.6, 2.7)

bin/publish-snapshots
It's broken because of the drivers.
=> cron: ignore latest snapshot (2.8.0-snapshot.20231213.0)

docs/3.0.0/docs/canton/usermanual/repairing.rst, docs/3.0.0/versions.json
Companion PR of https://github.com/DACH-NY/canton/pull/15823.
@digital-asset/daml-docs This section is essentially "JFYI" and anyway will evolve before 3.x because the UX of these tools has room for improvement. In any case, it is simpler now and I tried to reflect it in the docs.
=> Code fork, 3.x: port `RehydrationIntegrationTest`-related docs to X

docs/2.9.0/versions.json, docs/3.0.0/versions.json
Updates daml finance version for `2.9.0` and `3.0.0`.
=> Daml Finance: Update version

docs/2.9.0/docs/canton/includes/snippet_data/tutorials/getting_started.json, docs/2.9.0/docs/canton/includes/snippet_data/usermanual/connectivity.json, docs/2.9.0/docs/canton/includes/snippet_data/usermanual/identity_management.json, docs/2.9.0/docs/canton/includes/snippet_data/usermanual/manage_domain_entities.json, docs/2.9.0/docs/canton/includes/snippet_data/usermanual/manage_domains.json, docs/2.9.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json, docs/2.9.0/docs/canton/includes/snippet_data/usermanual/upgrading.json, docs/2.9.0/docs/canton/tutorials/getting_started.rst, docs/2.9.0/docs/canton/usermanual/apis.rst, docs/2.9.0/docs/canton/usermanual/console.rst, docs/2.9.0/docs/canton/usermanual/docker.rst, docs/2.9.0/docs/canton/usermanual/identity_management.rst, docs/2.9.0/docs/canton/usermanual/installation.rst, docs/2.9.0/docs/canton/usermanual/monitoring.rst, docs/2.9.0/docs/canton/usermanual/persistence.rst, docs/2.9.0/docs/canton/usermanual/repairing.rst, docs/2.9.0/docs/canton/usermanual/static_conf.rst, docs/2.9.0/docs/tools/sandbox.rst, docs/2.9.0/docs/tools/trigger-service/index.rst, docs/2.9.0/versions.json
Before, the installation guide was based on the advanced config example, which was guiding people through the process by starting with the simplest example and then calling out options.
Now, we start with a full example that comes with TLS, JWT, Storage etc, where a client can then decide to incrementally remove configurations instead.
The docs changes are related to https://github.com/DACH-NY/canton/pull/15882
=> Rewrote installation guide to use new reference config

docs/2.8.0/docs/getting-started/manual-download.rst, docs/2.9.0/docs/getting-started/manual-download.rst, docs/3.0.0/docs/getting-started/manual-download.rst
Split releases made this documentation slightly out of date - you have to use --install-with-custom-version to make an offline install work.
=> Document offline installation process using --install-with-custom-version

docs/2.8.0/docs/getting-started/manual-download.rst, docs/2.9.0/docs/getting-started/manual-download.rst
The way the page is currently written assumes that the only reason you might want to do a manual install is because you want to take the time to check the signature.
What seems to be a more prevalent case based on my interactions with Daml users is a need to install from a tarball on a machine that does not have internet access. Right now, that use-case requires reading the whole page and figuring out which steps you don't need to perform. It also makes the manual install look very scary at first glance.
In this PR, I have extracted (and slightly supplemented) the "just the install" steps to their own section, and left the signature verification steps largely untouched. I expect this is far from perfect and this page still needs a thorough pass by someone actually qualified to write …
=> reorganize manual install page

docs/2.7.6/docs/canton/usermanual/monitoring.rst, docs/2.8.0/docs/canton/usermanual/monitoring.rst, docs/2.9.0/docs/canton/usermanual/monitoring.rst
Nobody seems to know what this is meant to link to. Plus, as far as I can tell this is the only page on which we talk about metrics, so we don't really need a link.
=> remove dead link

docs/2.8.0/docs/support/releases.rst, docs/2.9.0/docs/support/releases.rst, docs/3.0.0/docs/support/releases.rst
Before this change, we didn't mention the support policy as per the new agreement. Now, we do. https://docs.google.com/document/d/14IS8ECgZWV9BEXBz1BU1gEwWaYsesTmNSbtoGPXAWGE/edit#heading=h.ydftn3ns7yuk
=> Updated support policy

docs/2.6.5/requirements.txt, docs/2.7.6/requirements.txt, docs/2.8.0/requirements.txt, docs/2.9.0/requirements.txt, docs/3.0.0/requirements.txt, docs/draft/requirements.txt
Sphinx 4.3.1 depends on "most recent applehelp", which since Aug 2023 requires Sphinx 5, so our current install is broken. (Same applies to a handful of other Sphinx deps.)
It took some time to surface as the old install was cached by CircleCI (and, likely, it's not affected anyone's local builds either for the same reason).
=> pin Sphinx deps

docs/2.7.6/docs/canton/usermanual/packagemanagement.rst, docs/2.8.0/docs/canton/usermanual/packagemanagement.rst, docs/2.9.0/docs/canton/usermanual/packagemanagement.rst
This has been true since 2.4.0 but apparently never fixed in the documentation.
=> Fix the error documented to report an unvetted package

docs/2.9.0/docs/canton/usermanual/upgrading.rst
Because the referenced conf file is going to be removed for Canton 2.9 and later.
This change is required for resolving this Canton issue: https://github.com/DACH-NY/canton/issues/15250
=> Replace file include with content

bin/publish-snapshots
The canton project is not pushing its docs sources anymore.
=> ignore daml3 snapshots

docs/2.8.0/docs/canton/usermanual/monitoring.rst, docs/2.9.0/docs/canton/usermanual/monitoring.rst, docs/3.0.0/docs/canton/usermanual/monitoring.rst
Removed executor metrics in [main-2.x](https://github.com/DACH-NY/canton/pull/16806)
and in main.
=> Removed Java Execution Service Metrics.

CODEOWNERS
@dylant-da has volunteered to get more involved in the maintenance of the technical side of this repo. I've created the @digital-asset/re team to provide us with a bit of flexibility should other people get involved in the future.
=> expand technical ownership

bin/publish-snapshots
We discovered a last-minute bug and will jump to 2.8.3 directly.
=> ignore 2.8.2

docs/2.9.0/docs/tools/daml-shell/index.rst
Daml docs style is to use sentence case for all headings except H1/page title
([item 13 in style quick ref](https://docs.google.com/document/d/153D6-gI0blsAvlrzReHVyz8RCHUQzzdKnxnpcADlt6c/edit#heading=h.74n7maw54ixb))
=> Make H2 sentence case

docs/2.9.0/_toc.yml, docs/2.9.0/docs/app-dev/bindings-java/quickstart.rst, docs/2.9.0/docs/app-dev/parties-users.rst, docs/2.9.0/docs/canton/tutorials/getting_started.rst, docs/2.9.0/docs/concepts/glossary.rst, docs/2.9.0/docs/daml/intro/12_Testing.rst, docs/2.9.0/docs/support/component-statuses.rst, docs/2.9.0/docs/tools/assistant.rst, docs/2.9.0/docs/tools/navigator/index.rst, docs/2.9.0/docs/tools/sandbox.rst
Part of https://github.com/digital-asset/daml/issues/18650
Daml PR: https://github.com/digital-asset/daml/pull/18748
docs.daml.com PR: https://github.com/digital-asset/docs.daml.com/pull/658
Originally, this PR also removed `daml navigator` from the 3.0.0 docs. However, that's a larger piece of work since the navigator is heavily referenced from a few tutorials so they will need to be reworked. I've thus split that off as https://github.com/digital-asset/docs.daml.com/pull/659.
=> Deprecate `daml navigator`

docs/2.7.9/docs/canton/usermanual/monitoring.rst, docs/2.8.3/docs/canton/usermanual/monitoring.rst, docs/2.9.0/docs/canton/usermanual/monitoring.rst, docs/3.0.0/docs/canton/usermanual/monitoring.rst
The docs at https://docs.daml.com/canton/usermanual/monitoring.html#logging say:
> `--log-profile=container` ...turns off flat file logging
> to avoid storage leaks due to log files within a container.
The wording, "turns off flat file logging" is ambiguous, since it could be interpreted as turning off logging to files. However, that is not the case. You can confirm with the following:
```
docker run --rm -it --volume ./log:/home/nonroot/log digitalasset-docker.jfrog.io/canton-enterprise:2.8.3 --no-tty -C canton.participants.participant1.ledger-api.address=0.0.0.0 -C canton.participants.participant1.ledger-api.port=5011 --log-profile container
exit()
more log/canton.log
```
This PR updates the docs to clarify the actual behavior.
=> Clarify description of the log-profile container option

docs/2.8.5/docs/json-api/lf-value-specification.rst
Fixes [#1919](https://github.com/digital-asset/daml/issues/19195)
For 2.x, document the difference in Java 11/17 `Timestamp` parsing for the JSON API.
=> make Timestamp parsing consistent across Java versions

docs/2.9.0/versions.json
In preparation for the upcoming `2.9.0` release we should update the `versions.json` to more recent version of the dependencies.
=> Bump docs/2.9.0 versions

docs/2.8.7/bin/setup-sphinx-source-tree
Details, see #719 
Fixes two release specific links for 2.8.7:
* [Windows download link](https://docs.daml.com/getting-started/installation.html#windows-10)
* [Use the Ledger API With gRPC – Get Started - protobuf download link](https://docs.daml.com/app-dev/grpc/#get-started)
=> Fix broken release links for 2.8.7 (#719)

docs/2.10.0/_toc.yml, docs/2.10.0/docs/canton/usermanual/kms/kms_driver_guide.rst, docs/2.10.0/versions.json, docs/2.9.0/_toc.yml, docs/2.9.0/docs/canton/usermanual/kms/kms_driver_guide.rst, docs/2.9.0/versions.json
Added the developer guide for KMS drivers with the API specification pulled in from the Canton repo and examples for a KMS driver test suite based on our AWS KMS driver. Both for 2.9 and 2.10
=> Added KMS Driver developer guide

bin/publish-snapshots
Publishing snapshots job fails because `2.9.0-rc1` because it points to a canton artefact  which does not include the `preview-version-support.conf`. 
```
Warning, treated as error:
/home/circleci/project/docs/2.9.0/workdir/build/source/source/canton/usermanual/FAQ.rst:176:Include file '/home/circleci/project/docs/2.9.0/workdir/build/source/source/canton/includes/mirrored/community/app/src/test/resources/documentation-snippets/preview-version-support.conf' not found or reading it failed
```
This adds it to the known broken releases.
CI job: https://app.circleci.com/pipelines/github/digital-asset/docs.daml.com/22688/workflows/0d2fabfa-2f04-442a-ba68-ef5f98156ab9/jobs/23438
=> Add 2.9.0-rc1 to known broken snapshots

docs/3.1/docs/canton/usermanual/apis.rst
Related to the changes made in https://github.com/DACH-NY/canton/pull/19944 for https://github.com/DACH-NY/canton/issues/19112.
=> Document the `logout` commands to revoke authentication tokens.

docs/2.10.0/docs/app-dev/services.rst, docs/2.9.4/docs/app-dev/services.rst, docs/3.1/docs/app-dev/services.rst
EQS has been marked as GA in version 2.9.x:
https://blog.digitalasset.com/developers/release-notes/2.9.1#:~:text=EventsByX%20is%20promoted%20to%20General%20Availability
=> Remove BETA marking from event query service

docs/2.10.0/docs/concepts/ledger-model/upgrade-model-in-depth.rst, docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
- Update the doc to mention LF 1.17 instead of 1.16
- Update the doc with the latest restrictions wrt to interfaces
=> Update daml 2.10's upgrade documentation with latest changes

docs/2.10.0/docs/canton/usermanual/persistence.rst, docs/2.8.9/docs/canton/usermanual/persistence.rst, docs/2.9.4/docs/canton/usermanual/persistence.rst, docs/3.1/docs/canton/usermanual/persistence.rst
In the guidance about tuning Postgres performance, the following phrase appears:
```
Also increase the following variables N times beyond their default
```
That has been (incorrectly) understood to mean there is some specific value of `N` to target. Later, the paragraph explains that one must "Monitor your system during load testing and tune the parameters accordingly to your use case."
I propose removing `N times` to avoid misunderstanding.
=> Remove "N times" from the Postgres tuning guidance

docs/2.10.0/docs/canton/usermanual/upgrading.rst, docs/2.9.4/docs/canton/usermanual/upgrading.rst
Adds missing content from the 2.9 Canton upgrading page to the 2.10 page. And then updates the one-step migration for 2.10.
Relates to:
*  https://github.com/DACH-NY/canton/issues/21074
=> Fix Canton upgrading page for 2.10

bin/publish-snapshots
Snapshot 2.10.0-snapshot.20241002.0 fails the docs.daml.com build because it refers to a Daml SDK snapshot which contains a broken proto-docs.rst.
This has been fixed with https://github.com/DACH-NY/canton/pull/21568 but it has not found its way into a new Daml SDK snapshot build yet.
=> Add 2.10.0-snapshot.20241002.0 to the broken snapshot releases

docs/2.10.0/versions.json
Updates the 'Ledger API Reference' page content presentation: https://docs.daml.com/2.10.0/app-dev/grpc/proto-docs.html
This also updates the Canton 2.10.0-snapshot dependency.
=> Update Daml 2.10.0-snapshot dependency to update the LAPI reference docs

README.md
Change the README to ask users to send an e-mail to help@digitalasset.com instead of pinging on Slack directly.
=> Small fix to onboarding documentation for this repo.

bin/publish-snapshots
Because it refers to Daml SDK which contains a LAPI Reference Documentation RST that contains invalid RST, and thus breaks the build.
=> Add 2.10.0-snapshot.20241016.0 to known broken releases

theme/js/theme.js
You may have noticed a very annoying behavior when clicking on links within the Ledger API reference docs. For example, if you click on the link for the [GetActiveContractsResponse message](https://docs.daml.com/app-dev/grpc/proto-docs.html#com-daml-ledger-api-v1-getactivecontractsresponse), the heading for that message is _behind_ the navbar. It is very confusing for new users.
This PR makes a small CSS tweak to address that issue. Using jQuery, it dynamically adds the `section` CSS class to the `span`s which serve as the anchor for internal links.
I did look at trying to add that CSS class to the RST source file, but without success. I have also [asked on StackOverflow](https://stackoverflow.com/questions/79091778/add-css-class-to-sphinx-generated-anchor-span).
Attached are videos …
=> Fix scroll position for cross references links

docs/2.10.0/docs/upgrade/upgrade-scopes.csv
Before this change, we still had interfaces as being upgradable. Now, we are explicit about that interfaces and exceptions are static.
=> Updated SC upgrading limitations

docs/2.10.0/docs/canton/usermanual/persistence.rst, docs/2.10.0/docs/canton/usermanual/troubleshooting_guide.rst, docs/2.9.5/docs/canton/usermanual/persistence.rst, docs/3.1/docs/canton/usermanual/persistence.rst
Before this change, we didn't have a section in the manual saying that cloud resources are going to give you less predictable behaviour. Now, we have one.
I will copy it to the other versions after the review here.
=> Added a sentence on the impact of cloud resources

docs/2.9.5/docs/app-dev/command-deduplication.rst, docs/2.9.5/versions.json
Ports the changes to the LAPI Reference Documentation also to 2.9.
Related to
1. https://github.com/DACH-NY/canton/pull/22115
2. https://github.com/digital-asset/daml/pull/20202
3. https://github.com/digital-asset/daml/pull/20208
4. https://github.com/digital-asset/docs.daml.com/pull/814
=> Backport 'Update LAPI Reference Documentation' to 2.9

README.md, bin/list-outdated-files
@carrielaben-da suggested in a discussion:
> A nice-to-have for me: some mechanism that can flag pages that have not been updated within the past year as candidates for audit. Occasionally we have outdated material that persists because there hasn't been a PR that explicitly removes it (e.g. the old docs on supporting Ethereum and Hyperledger Fabric.)
Basic usage:
```
./bin/list-outdated-files
```
Customized usage:
```
./bin/list-outdated-files -l 3.months -d docs/3.1/docs -e json -o gitlog
```
Help:
```
./bin/list-outdated-files -h
```
=> Add a script for listing outdated files

docs/3.1/docs/canton/usermanual/identity_management.rst, docs/3.1/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/implementing-ha.rst, docs/3.1/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/introduction.rst, docs/3.1/docs/deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling/use-cases.rst
Fixes five instances of synchronizer being spelled wrong.
=> Remover "syncrhonizer" typo

bin/publish-snapshots
Because it refers to canton 2.10.0-snapshot.20241118.12344.0.v7d331e04 which does not include a required source file from Canton that is referenced by the decommissioning.rst RST file.
Details:
https://app.circleci.com/pipelines/github/digital-asset/docs.daml.com/26865/workflows/234a748c-937b-4af2-a317-49b3d2dd0041/jobs/27706
=> Add 2.10.0-snapshot.20241120.0 to known broken releases

docs/2.10.0/README.md, docs/2.10.0/docs/app-dev/explicit-contract-disclosure.rst, docs/2.10.0/docs/canton/architecture/domains/domains.rst
Add some styling improvement and missing updates taken from 3.1, while I was comparing diffs between 2.10 and 3.1.
=> Copy minor doc updates from 3.1 to 2.10

docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
This updates the upgrades documentation with the following UPDs:
- UPD-3: Use `daml-script-beta` over `daml-script`
- UPD-4: Daml script binary no longer needs `--enable-contract-upgrading`
- UPD-7: "Per-submission package preference" limitation on daml studio was fixed, can be removed
- On updating this, I found all other daml-studio limitations were addressed, and removed them
- UPD-8: script doubleIOU is defined nowhere
- Could @remyhaemmerle-da or @dylant-da verify this.
=> Update upgrade docs with latest information

docs/2.10.0/docs/daml/daml-studio.rst, docs/2.10.0/docs/tools/assistant-build.rst, docs/2.10.0/docs/tools/assistant.rst, docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
There is a note about 2.10rc limitations, we will fix them in the 2.10 full release, but assuming we'll give these docs to the testers of the rc, its worth noting there.
I've mostly replaced the sdk-version only daml.yaml, as its main purpose is replaced by multi-ide. It still has use, but we may replace that too.
=> Add docs for Multi-Package Daml Studio support

docs/2.10.0/docs/tools/assistant-build.rst, docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
Document usage of multi-package builds for upgrades. We use the upgrades-example template, introduced https://github.com/digital-asset/daml/pull/20385 and https://github.com/digital-asset/daml/pull/20450
Addresses upgrade documentation task UPD-23
=> Document multi-package builds for upgrades via upgrades-example template

docs/2.10.0/docs/upgrade/upgrade-scopes.csv
Used to look like this:
Now looks like this:
=> Fix upgrade table formatting

docs/2.8.11/docs/canton/usermanual/console.rst, docs/2.9.5/docs/canton/usermanual/console.rst
https://github.com/DACH-NY/canton/issues/22681
Note that for `2.10` and `3.x` we will fix the configuration to unify the config options, so this comment in the remote console docs is not required.
=> #22681 Improve docs for TLS options of remote console

docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
From fields in: https://docs.google.com/spreadsheets/d/1_0ER--x-YJzoYSoy7VFs6emzn4ZYjBc0kte4MLosuxs/edit
Each commit addresses something different:
- 03ca9c58fcdffd3da212b2d726f29793bc787c97 updated the docs that used to state that deps are only checked on the participant - they are now checked on the compiler as well, so I've updated the docs there and made them easier to understand.
- e11bbd330e458e737d156e903ffb7d93e525deaf is a trivial fix to `sdk-version: 0.0.0` -> `sdk-version: 2.10.0`
- 81700d6057238b4c79e6c96e3c78ae6cbdbd2b43 addresses UPD-12 by improving the section on best practice for interface/template splitting, and documenting the flags that affect this. There are still some other flags for upgrade warnings/errors, so there will be more to come.
- …
=> Document for UPD-12, UPD-30, UPD-33, and improve docs for deps upgrade checks

CODEOWNERS
This reduces the PR review notifications for the docs.daml.com maintainer team `re` who are interested in reviewing non-documentation content only.
=> Request PR reviews for docs content only from the docs team

CODEOWNERS
This reduces PR review notifications for the docs.daml.com maintainer team `re` who are only interested in reviewing non-documentation content.
On the other hand, any change to a file located in the `/docs` directory and its subdirectories requires an approval from the docs team.
=> Improve `CODEOWNERS` to reduce PR approval notification noise

docs/2.10.0/docs/canton/usermanual/console.rst
Little doc update for TLS config for 2.10+, corresponds to https://github.com/DACH-NY/canton/pull/23017
=> #22681 Document `tls.enabled` for in 2.10

docs/2.10.0/docs/canton/usermanual/upgrading.rst
Also, emphasize `--manual-start` command line option in common upgrade instructions.
Addresses https://github.com/DACH-NY/canton/issues/22755
=> Add 2.10 upgrade instructions.

docs/2.10.0/docs/canton/includes/snippet_data/usermanual/packagemanagement.json, docs/2.10.0/docs/canton/usermanual/packagemanagement.rst
@mziolekda @rgugliel-da @simonmaxen-da The main purpose of this PR is:
- document the package topology state and UX after the introduction of tri-state vetting
- prepare this section for an LTS Canton version. More specifically, I thought of cleaning up references to unsupported operations such as DAR and package removal. We will still have endpoints supporting these but we don't advertise them
Hint for reviewing: Since it also has code snippets, `live-preview` is not enough for reviewing this PR. I advise reviewers to use `docs/2.10.0/bin/build`
=> [Tri-state vetting] Package management docs updates

docs/2.10.0/docs/single-domain/extend-model.rst, docs/2.10.0/docs/upgrade/smart-contract-upgrades.rst
Decided together with @meiersi-da and @hrischuk-da to remove as it's not targeting general enough use cases and might lead to confusion. CC @remyhaemmerle-da
=> Remove Explicit Template Versions from upgrading docs

docs/2.10.0/docs/daml/reference/interfaces.rst, docs/2.7.9/docs/daml/reference/interfaces.rst, docs/2.8.12/docs/daml/reference/interfaces.rst, docs/2.9.6/docs/daml/reference/interfaces.rst, docs/3.1/docs/daml/reference/interfaces.rst
Update config requirement for interfaces since DAML LF 1.15 is already the default from version 2.6.0.
=> Remove '--target=1.15' requirement.

docs/2.10.0/bin/setup-sphinx-source-tree, docs/2.8.12/bin/setup-sphinx-source-tree, docs/2.9.6/bin/setup-sphinx-source-tree
The docs.daml.com copyright notice is taken from the Daml SDK source tree artifact. Thus, updating the copyright year means to create a new Daml SDK release artifact. Doing so is **_very_** time-consuming.
Instead, the source tree setup script is now going to update the copyright year based on the current year.
=> Add copyright update to the source tree scripts for 2.10.0, 2.9.6, 2.8.12

docs/2.10.0/docs/canton/usermanual/upgrading.rst
The recommended protocol version for 2.10 is 7. Thus, the 'One-Step Migration' guide should not suggest that protocol version 5 is recommended for 2.10.
=> Consistent protocol version recommendation for 2.10

docs/2.10.0/docs/canton/usermanual/upgrading.rst
~This PR changes the heading "One-Step Migration Recipe for 2.10" to simply "Migration Recipe for 2.10".~ _EDIT: This PR adds a new short paragraph to more explicitly define the term "one-step migration."_
~The original intent of the heading was probably based on the idea of a single migration step from any 2.3+ directly to 2.10, instead of having to go through each intermediate major release version.~ _Edit: this is wrong, as discussed in the comments._
However, the text itself uses "steps" to enumerate the steps of the recipe. The reader may not understand what was meant by the current heading.
=> Add clarifying paragraph to One-Step Migration

docs/2.10.0/docs/canton/usermanual/contract_keys.rst
In response to support request https://support.digitalasset.com/s/case/500Pq00000Yt5d1IAB/question-about-the-docs-on-workarounds-for-recovering-uniqueness
* The `Generator` approach also works in the multiple participant settings.
* The `KeyState` approach works under delegation of `Keyed` non-consuming choices 
I do believe that the `Generator` approach would even work for multiple maintainers under certain trust assumptions in a single-domain setting. I don't want to flesh this out right now though.
=> [8946] update contract key uniqueness caveats

docs/2.10.2/docs/daml/reference/data-types.rst, docs/2.9.7/docs/daml/reference/data-types.rst, docs/3.1/docs/daml/reference/data-types.rst
`BigNumeric` was [deprecated](https://blog.digitalasset.com/developers/release-notes/2.9.1) with 2.9.1. This PR indicates that in [the 2.x docs](https://docs.daml.com/daml/reference/data-types.html).
Related PRs:
* 2.x docs: https://github.com/digital-asset/docs.daml.com/pull/943
* 3.3 docs: https://github.com/digital-asset/daml/pull/21726
* 3.x docs: https://github.com/digital-asset/daml/pull/21725
=> Mark BigNumeric as deprecated in the 2.x docs
